env:
  node: true
  browser: true
  commonjs: true
  es2021: true
extends:
  - plugin:react/recommended
  - airbnb-base
overrides: []
parserOptions:
  ecmaVersion: latest
plugins:
  - react
rules:
  no-console: 0
  import/extensions: # FIXME: remove when rule will be adjusted for new nodejs version
    - error
    - ignorePackages
    - js: always
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
